name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities

version: 3.1.10

homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.1
  dots_indicator: ^3.0.0
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
