name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 3.0.2
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^2.1.0
  collection: ^1.15.0
